
//construction
export const ADD_CONSTRUCTION = "ADD_CONSTRUCTION";
export const REMOVE_CONSTRUCTION = "REMOVE_CONSTRUCTION";
export const GET_CONSTRUCTIONS = "GET_CONSTRUCTIONS";

//selection
export const SET_SELECTION = "SET_SELECTION";
export const DESELECT_ALL_OBJECTS = "DESELECT_ALL_OBJECTS";
export const APPEND_SELECTION = "APPEND_SELECTION";
export const GET_SELECTED_OBJECTS = "GET_SELECTED_OBJECTS";
export const GET_SELECTED_OBJECT_TYPES = "GET_SELECTED_OBJECT_TYPES";

//fetch
export const GET_RENDERER = "GET_RENDERER";
export const FETCH_SURFACES = "FETCH_SURFACES";
export const GET_CONTAINERS = "GET_CONTAINERS";
export const FETCH_CONTAINER = "FETCH_CONTAINER";
export const FETCH_ROOMS = "FETCH_ROOMS";
export const FETCH_ALL_SOURCES = "FETCH_ALL_SOURCES";
export const FETCH_ALL_SOURCES_AS_MAP = "FETCH_ALL_SOURCES_AS_MAP";
export const FETCH_ALL_RECEIVERS = "FETCH_ALL_RECEIVERS";
export const FETCH_SOURCE = "FETCH_SOURCE";

//settings
export const SETTING_CHANGE = "SETTING_CHANGE";
export const FETCH_ALL_SETTINGS = "FETCH_ALL_SETTINGS";
export const FETCH_SETTINGS__GENERAL = "FETCH_SETTINGS__GENERAL";
export const FETCH_SETTINGS__EDITOR = "FETCH_SETTINGS__EDITOR";
export const FETCH_SETTINGS__KEYBINDINGS = "FETCH_SETTINGS__KEYBINDINGS";
export const SUBMIT_ALL_SETTINGS = "SUBMIT_ALL_SETTINGS";
export const SUBMIT_SETTINGS__GENERAL = "SUBMIT_SETTINGS__GENERAL";
export const SUBMIT_SETTINGS__EDITOR = "SUBMIT_SETTINGS__EDITOR";

//materials
export const FETCH_ALL_MATERIALS = "FETCH_ALL_MATERIALS";
export const SEARCH_ALL_MATERIALS = "SEARCH_ALL_MATERIALS";
export const ASSIGN_MATERIAL = "ASSIGN_MATERIAL";

//adding objects/solvers
export const SHOULD_ADD_RAYTRACER = "SHOULD_ADD_RAYTRACER";
export const SHOULD_ADD_RT60 = "SHOULD_ADD_RT60";
export const SHOULD_ADD_FDTD = "SHOULD_ADD_FDTD";
export const SHOULD_ADD_FDTD_2D = "SHOULD_ADD_FDTD_2D";
export const SHOULD_ADD_SOURCE = "SHOULD_ADD_SOURCE";
export const SHOULD_ADD_RECEIVER = "SHOULD_ADD_RECEIVER";
export const SHOULD_ADD_SKETCH = "SHOULD_ADD_SKETCH";

//remove
export const SHOULD_REMOVE_SKETCH = "SHOULD_REMOVE_SKETCH";
export const SHOULD_REMOVE_SOLVER = "SHOULD_REMOVE_SOLVER";
export const SHOULD_REMOVE_CONTAINER = "SHOULD_REMOVE_CONTAINER";


//raytracer
export const RAYTRACER_CALCULATE_RESPONSE = "RAYTRACER_CALCULATE_RESPONSE";
export const RAYTRACER_QUICK_ESTIMATE = "RAYTRACER_QUICK_ESTIMATE";
export const RAYTRACER_SHOULD_PLAY = "RAYTRACER_SHOULD_PLAY";
export const RAYTRACER_SHOULD_PAUSE = "RAYTRACER_SHOULD_PAUSE";
export const RAYTRACER_SHOULD_CLEAR = "RAYTRACER_SHOULD_CLEAR";
export const RAYTRACER_SOURCE_CHANGE = "RAYTRACER_SOURCE_CHANGE";
export const RAYTRACER_RECEIVER_CHANGE = "RAYTRACER_RECEIVER_CHANGE";


export const CAN_DUPLICATE = "CAN_DUPLICATE";
export const SHOULD_DUPLICATE_SELECTED_OBJECTS = "SHOULD_DUPLICATE_SELECTED_OBJECTS";

//file io
export const IMPORT_FILE = "IMPORT_FILE";

//events

export const ADDED_SOURCE = "ADDED_SOURCE";
export const ADDED_RECEIVER = "ADDED_RECEIVER";
export const ADDED_RAYTRACER = "ADDED_RAYTRACER";
export const ADDED_RT60 = "ADDED_RT60";
export const ADDED_FDTD = "ADDED_FDTD";
export const ADDED_FDTD_2D = "ADDED_FDTD_2D";

export const ADDED_ROOM = "ADDED_ROOM";
export const ADDED_AUDIO_FILE = "ADDED_AUDIO_FILE";
export const APP_MOUNTED = "APP_MOUNTED";
export const RENDERER_UPDATED = "RENDERER_UPDATED";



//project actions
export const NEW = "NEW";

//history
export const CAN_UNDO = "CAN_UNDO";
export const CAN_REDO = "CAN_REDO";
export const UNDO = "UNDO";
export const REDO = "REDO";
export const CUT = "CUT";
export const PASTE = "PASTE";
export const COPY = "COPY";

//editor
export const MOVE_SELECTED_OBJECTS = "MOVE_SELECTED_OBJECTS";

export const PHASE_OUT = "PHASE_OUT";
export const STOP_OPERATIONS = "STOP_OPERATIONS";

export const SET_EDITOR_MODE = "SET_EDITOR_MODE";
export const GET_EDITOR_MODE = "GET_EDITOR_MODE";

export const SET_PROCESS = "SET_PROCESS";
export const GET_PROCESS = "GET_PROCESS";

export const SET_PROJECT_NAME = "SET_PROJECT_NAME";
export const GET_PROJECT_NAME = "GET_PROJECT_NAME";

//saving
export const SAVE = "SAVE";
export const SAVE_CONTAINERS = "SAVE_CONTAINERS";
export const SAVE_SOLVERS = "SAVE_SOLVERS";

export const OPEN = "OPEN";


export const RESTORE = "RESTORE";
export const RESTORE_CONTAINERS = "RESTORE_CONTAINERS";
export const RESTORE_SOLVERS = "RESTORE_SOLVERS";


//renderer
export const RENDERER_SHOULD_CHANGE_BACKGROUND = "RENDERER_SHOULD_CHANGE_BACKGROUND";
export const RENDERER_SHOULD_CHANGE_FOG_COLOR = "RENDERER_SHOULD_CHANGE_FOG_COLOR";
export const TOGGLE_CAMERA_ORTHO = "TOGGLE_CAMERA_ORTHO";
export const FOCUS_ON_SELECTED_OBJECTS = "FOCUS_ON_SELECTED_OBJECTS";
export const FOCUS_ON_CURSOR = "FOCUS_ON_CURSOR";
export const LOOK_ALONG_AXIS = "LOOK_ALONG_AXIS";

//ui
export const TOGGLE_RENDERER_STATS_VISIBLE = "TOGGLE_RENDERER_STATS_VISIBLE";
export const GET_RENDERER_STATS_VISIBLE = "GET_RENDERER_STATS_VISIBLE";
export const SET_OBJECT_VIEW = "SET_OBJECT_VIEW";
export const SHOW_TOAST = "SHOW_TOAST";
export const SHOW_NEW_WARNING = "SHOW_NEW_WARNING";
export const SHOW_OPEN_WARNING = "SHOW_OPEN_WARNING";
export const SHOW_TERMINAL = "SHOW_TERMINAL";
export const TOGGLE_TERMINAL = "TOGGLE_TERMINAL";
export const OPEN_MATERIAL_SEARCH = "OPEN_MATERIAL_SEARCH";
export const SHOW_SETTINGS_DRAWER = "SHOW_SETTINGS_DRAWER";
export const TOGGLE_MATERIAL_SEARCH = "TOGGLE_MATERIAL_SEARCH";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
export const SHOW_IMPORT_DIALOG = "SHOW_IMPORT_DIALOG";
export const SHOW_SAVE_DIALOG = "SHOW_SAVE_DIALOG";
export const SHOW_SAVE_DIALOG_THEN_OPEN = "SHOW_SAVE_DIALOG_THEN_OPEN";
export const GUTTER_SHOULD_UPDATE = "GUTTER_SHOULD_UPDATE";
export const SET_RENDERER_SHOULD_ANIMATE = "SET_RENDERER_SHOULD_ANIMATE";

//vars
export const ADD_SELECTED_OBJECTS_TO_GLOBAL_VARIABLES = "ADD_SELECTED_OBJECTS_TO_GLOBAL_VARIABLES";


//stats
export const STATS_SETUP = "STATS_SETUP";
export const STATS_UPDATE = "STATS_UPDATE";

//null
export const NULL = "NULL";

export const CLEAR_LOCAL_STORAGE = "CLEAR_LOCAL_STORAGE";


