export enum Processes {
  PICKING_SURFACE = "PICKING_SURFACE",
  PICKING_SOURCE = "PICKING_SOURCE",
  PICKING_RECEIVER = "PICKING_RECEIVER",
  SMOOTHING_CAMERA = "SMOOTHING_CAMERA",
  NONE = "NONE"
}
