export enum Processes {
  PICKING_SURFACE = "PICKING_SURFACE",
  PICKING_SOURCE = "PICKING_SOURCE",
  PICKING_RECEIVER = "PICKING_RECEIVER",
  PICKING_PLANAR_SURFACE = "PICKING_PLANAR_SURFACE",
  PICKING_AXIS = "PICKING_AXIS",
  PICKING_VERTEX = "PICKING_VERTEX",
  SMOOTHING_CAMERA = "SMOOTHING_CAMERA",
  NONE = "NONE"
}
